FROM python:3.8

COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip &&\
    pip install --no-cache-dir -r requirements.txt &&\
    pip uninstall -y tensorflow==2.6 &&\
    pip install --no-cache-dir tensorflow-cpu==2.4