name: Build API server container
on:
  push:
    branches: [ main, feature/kubernetes ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push api-server
        id: api-server
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./fastapi_Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project:api-server-1.0

      - name: Build and push prefect-worker
        id: prefect-worker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./prefect_Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project:prefect-worker-1.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
