name: Build API server container
on:
  push:
    branches: [ main, feature/CD_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push api-server
        id: api-server
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fastapi
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project:api-server-1.0

      - name: Build and push prefect-worker
        id: prefect-worker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.prefect
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mlops-project:prefect-worker-1.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            kubectl rollout restart -f ./MLOps/k8s/prepi_deployments.yaml